### ISSUE TITLE
add custom analytics

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#13]
- create a schema for adding custom analytics which include successful converts, unsuccessful converts, (hence total converts) and the number of visits on the page.

**Comment by Ashleyt28** [comment]
May I help by adding real-time API counting number of visits on the page?

**Comment by AnirudhGoel** [comment]
he wants to track the successful and unsuccessful runs of the converter, not the user count.

**Comment by JamesDelmai1195** [comment]
"and the number of visits on the page" ?

**Comment by Ashleyt28** [comment]
"and the number of visits on the page" ?

**Comment by JamesDelmai1195** [comment]
Sounds legit for me , why not implement a number of visits on the page.
