### ISSUE TITLE
Show relevant error message when file input is empty

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#14]
There is an HTML ```required``` attribute in ```input file```
If user removes it and tries to click on **Get Conversations** button there is an unexpected behaviour, instead user should get a relevant error message

**Comment by Pro-Ice** [comment]
Terribly sorry for the commit mess in the history. I've accidentally pushed to master and there's no way to delete commits from GitHub even if you've rebased them.

**Comment by prabhakar267** [comment]
@Pro-Ice you can always do a (hard) reset 
Read more about it here, https://git-scm.com/docs/git-reset

**Comment by prabhakar267** [comment]
Fixed in #20
