### ISSUE TITLE
Give option to store and restore chat to a local system

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#16]
Give an option download the JSON which is response from AJAX call to be restored in future.

**Comment by dannyverp** [comment]
Hey guys, I'd like to pick this issue up over the weekend

**Comment by dannyverp** [comment]
The first PR adds the option to download the created JSON. I'm now working on an option to upload it.

**Comment by dannyverp** [comment]
The second MR adds the option to upload a previously downloaded JSON. Let me know if this seems alright :)
