### ISSUE TITLE
Clear Error messages div whenever new request is submitted

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#22]
Current Behaviour:
If there were errors in existing request and you make another request which is successful, the errors div still shows errors from previous request.

Expected Behaviour:
On every request submission, errors div should be cleared

**Comment by vikaskyadav** [comment]
use show and hide functions if you are using jQuery.

**Comment by prabhakar267** [comment]
Instead of fading out or show-hide, we can clear out ```#errors``` div on every button submit

**Comment by prabhakar267** [comment]
Fixed in #23
