### ISSUE TITLE
Chat couldn't be parsed due to changes in the file format or variations based on user settings.

### ISSUE THREAD

**Issue by nilsweb** [prabhakar267/WA-Reader#25]
Hey there,
I just tired parsing a chat history but couldn't get it to work. After some investigation, I found out that the file format WhatApp uses when exporting the chat history seems to have changed.

My export looks something like this:
```
6/23/17, 12:29:34 PM: Person 1: This is a message from Person 1.
6/23/17, 12:30:04 PM: Person 2: This is a message from Person 2.
```

Compared to the export supplied in the sample directory:
```
13/10/2017, 12:12 a.m. - Person 1: Do I really look like a guy with a plan?
13/10/2017, 12:12 a.m. - Person 1: You know what I am? I'm a dog chasing cars.
```

To me it looks like the delimiter between the timestamp and the message has been changed from `-` to `: `. Is this also the case for you or could it be that WhatsApp uses a different format based on region settings and platform? I tried it with region set to "United States" on iOS 11 using the most recent version of WhatApp.

If this varies from user to user, I would come up with a system that could auto-detect the used format or provides the user witch an option to select from. Otherwise I would modify the current parsing algorithm to reflect this change in the file format.

**Comment by moi247** [comment]
Suggested fix with patch: [https://github.com/moi247/WA-Reader/tree/patch-1](url)

This only fixes the issue for the current format, but as mentioned, regex would be a more foolproof fix

**Comment by prabhakar267** [comment]
@moi247 Thank you for your concern. You can probably initiate a PR for this issue and we can discuss your solution on that
I saw your patch, it would work fine for this particular instance but it won't work for all the older files. Maybe an initial check for the presence of potential delimiter ("-" or ":") in the string solve this problem
