### ISSUE TITLE
Local Machine: Some technical glitch! Please retry after reloading the page!

### ISSUE THREAD

**Issue by sarnic** [prabhakar267/WA-Reader#27]
Hi,

I downloaded your project as zip and try to use it, I get the error: Some technical glitch! Please retry after reloading the page!

If I use your web page, it work's fine.

Is there any references which I have to adapt so I can also use it on local machine?

**Comment by prabhakar267** [comment]
@sarnic I don't think there should be any issue with the local setup
Still I think if you can enable debugging and see if you can detect the problem.

It would be a good thing to add this as a section in README.md

**Comment by sarnic** [comment]
@prabhakar267 
when i try to load my file, i get the following error message:
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by prabhakar267** [comment]
Tracking in #30
