### ISSUE TITLE
Some Emoticons missing

### ISSUE THREAD

**Issue by sarnic** [prabhakar267/WA-Reader#29]
Hi,

I have noticed that there are missing several emoticons.
How I can add them?

**Comment by prabhakar267** [comment]
@sarnic 
The front end code uses [minEmoji](https://github.com/rodrigopolo/minEmoji) for convert emoji text to emoji sprite image. 
If you could share what emoticons are missing, we can either raise an issue with minEmoji repo or if it can be handled at our end, we can do that

**Comment by sarnic** [comment]
i will add the missing one in the next days.

**Comment by prabhakar267** [comment]
Seems this is fixed. Please feel free to reopen if issue persists.
