### ISSUE TITLE
Add local setup instructions in README

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#30]
Setup Instructions can be a good addition to the readme (or any other appropriate file) for anyone to have a local version of the app to view any sensitive information.
It should include the instructions to enable debugging in PHP as mentioned in [upload-file.php](https://github.com/prabhakar267/WA-Reader/blob/master/parse/upload-file.php#L5)

**Comment by mndoow** [comment]
How long it will take?
