### ISSUE TITLE
WA Chat History txt file is not opening.-Backup from IOS

### ISSUE THREAD

**Issue by sufyanraza66** [prabhakar267/WA-Reader#32]
I backup a chat history from my iPhone6 IOS 11.3.
WA is not supportable for this file. 
I'm facing an issue while reading a txt file of Whatsapp chat history, backup form iPhone. WA supports iPhone WA history txt file or not ? if yes. kindly fix the issue. 
**It wasn't a valid text file or we were not able to convert it** 
A sample WA chat txt file is attached for test purpose. 

[_chat.txt](https://github.com/prabhakar267/WA-Reader/files/1893117/_chat.txt)

@prabhakar267

**Comment by prabhakar267** [comment]
@sufyanraza66 WA Reader works for your chat now :+1:
