### ISSUE TITLE
WA Reader display only the first sentence

### ISSUE THREAD

**Issue by Francisco6x** [prabhakar267/WA-Reader#33]
If a message it is like this, it works fine:
WA Reader is a platform to read WhatsApp conversations from email text backups in a easy-to-read UI. 

But, if message it is divided into sentences, it display only the first sentence:
WA Reader is a platform to read WhatsApp conversations.
From email text backups.
In a easy-to-read UI. 
It display only:
WA Reader is a platform to read WhatsApp conversations.

A small piece of chat:
[Conversa do WhatsApp com Luiz Américo.txt](https://github.com/prabhakar267/WA-Reader/files/1916280/Conversa.do.WhatsApp.com.Luiz.Americo.txt)

**Comment by prabhakar267** [comment]
@Francisco6x WA Reader works for your chat now :+1:
