### ISSUE TITLE
"It wasn't a valid text file or we were not able to convert it"

### ISSUE THREAD

**Issue by Blackbird2106** [prabhakar267/WA-Reader#35]
After uploading my file to https://whatsapp-reader.herokuapp.com/ the following error appeared: "It wasn't a valid text file or we were not able to convert it".
My chat file seams to have a different timestamp format, than your sample file. 
So here is a part of my file:

```
27.01.14 23:38:13: Dude: hi

27.01.14 23:40:57: Myself: hi

28.01.14 23:48:54: Myself: whats up?
```

Don't know if that is important, but the empty lines are not showing in Microsoft Notepad.
If I open it with Notepad++ it shows the empty lines though.

Thank you for your hard work!
D.M.

**Comment by prabhakar267** [comment]
![image](https://user-images.githubusercontent.com/10768588/120099561-be117f80-c159-11eb-8778-db83a8d233ac.png)
This got fixed. Closing the issue
