### ISSUE TITLE
Some technical glitch! Please retry after reloading the page!

### ISSUE THREAD

**Issue by mndoow** [prabhakar267/WA-Reader#37]
I'm getting this error while I try to "Get Conversation", I already used Chrome, Firefox, Chrome and Internet Explorer, I'm doing something wrong?

Regards and thanks in advance!

**Comment by prabhakar267** [comment]
@mndoow Did you get this error on the hosted version or did you make a local copy and got this error?

**Comment by mndoow** [comment]
Thanks a lot for your re ply Prabhakar267, could you please give me any info on how to properly use it? I guess I'm doing it wrong

**Comment by prabhakar267** [comment]
I will try to add a local setup guide
I had opened a separate issue #30 for the same, hence closing this!
Once that setup guide is up, you will be able to debug this 👍
