### ISSUE TITLE
Timestamps not parsed

### ISSUE THREAD

**Issue by seashehl** [prabhakar267/WA-Reader#40]
Hello, I have just discovered your wonderful tool. It is perfect and exactly what I needed, so thank you. There is just one problem I am encountering. The timestamps are showing up as a sequence of digits. Your example on your page here https://devpost.com/software/whatsapp-reader shows the timestamp in the correct format. 

I have attached an image of what i am seeing, (I have scored out the actual text)

I would just like to know if this is as intended, or if there is something wrong with my exported whatsapp files, or if this is a bug. Is there any way I can view the chat with the timestamps?
![whatsappchat](https://user-images.githubusercontent.com/43845036/46464955-804cd500-c7bf-11e8-917e-c6425d4481fa.png)

**Comment by prabhakar267** [comment]
@edsac  Can you open a PR for the same?

**Comment by Suleman-Elahi** [comment]
I think this is the same reasons why it is not working on chat backup taken on Windows phone.

**Comment by prabhakar267** [comment]
@seashehl It should work now properly. Please feel free to reopen this issue or open a new one if you face any problem.
