### ISSUE TITLE
Whats app chat can´t be read by the program

### ISSUE THREAD

**Issue by markgark** [prabhakar267/WA-Reader#42]
[WhatsApp Chat - Panzon.txt](https://github.com/prabhakar267/WA-Reader/files/2897378/WhatsApp.Chat.-.Panzon.txt)

iOS, Iphone 6

**Comment by prabhakar267** [comment]
@markgark Attached file doesn't look like a `.txt` file

**Comment by markgark** [comment]
prabhakar, yes I Know. I exported a whatsapp chat from iphone. I do not understand why it doesn't like a txt file or why it is crypted.

**Comment by prabhakar267** [comment]
@markgark I tried parsing this file, but this is not in valid text format. 
Closing the issue.
