### ISSUE TITLE
Trouble with european Date!!

### ISSUE THREAD

**Issue by ColinJoerg** [prabhakar267/WA-Reader#45]
Here are the dates link DD/MM/YYYY..... with the dirty timestamps, the script change 05.09 to 09.05 but 13.09.
dateutil has the option "dayfirst=True", would be helpfully ;-)

**Comment by prabhakar267** [comment]
Can you upload a small sample?
I would like to test the `dayfirst` option

**Comment by ColinJoerg** [comment]
29/10/2018, 12:17 - Peter: Ok will do
30/10/2018, 16:23 - Peter: Memorandum of Test
05/11/2018, 15:41 - Ian: Ok so let's go to Munich
05/11/2018, 15:44 - Ian: where do we go exactly?
05/11/2018, 15:44 - Ian: I have no details.

With:

timestamp_string = parse_datetime((dirty_timestamp_string), dayfirst=True)

it works perfect for me ;-)
