### ISSUE TITLE
[BUG] Throws an exception when a route other than base route is opened

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#52]
## Description
It throws an error whenever you open any route other than base route `/`

## Expected behaviour
Should redirect the user to base route with the following error message:
`"Sorry, we couldn't find the page"`

**Comment by sapnatomar** [comment]
I want to work on this issue.

**Comment by sapnatomar** [comment]
I would like to take up this issue.

**Comment by sapnatomar** [comment]
Hey @prabhakar267, please review this pull request #59 .

**Comment by prabhakar267** [comment]
Fixed in #59
