### ISSUE TITLE
[Logo Design] Design a new logo 

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#53]
Current logo was created as a temporary placeholder. Design a new logo with captures the product.
I would like to use the logo without any legal formalities but would definately be giving a huge shout out to the designer on the website and GitHub repository 

## Current Logo 
<img src="https://whatsapp-reader.herokuapp.com/static/img/logo.png" width="50%" />

### All suggestions are welcome 😄

**Comment by krzysiekh** [comment]
Hi, 
I've created PR with sample logo design.
