### ISSUE TITLE
Bug in group conversations

### ISSUE THREAD

**Issue by prachi1210** [prabhakar267/WA-Reader#6]
In group conversations, there is no way to differentiate which message is by whom. All text messages by different group members are clustered together under the same colour.

![image](https://cloud.githubusercontent.com/assets/14016564/14923054/829b0da4-0e58-11e6-8364-ad5902fe429e.png)

**Comment by prabhakar267** [comment]
@prachi1210 does #8 resolves the issue?

**Comment by prachi1210** [comment]
@prabhakar267 The users were being displayed earlier was well. What isn't clear is what message was sent by which user, since they are all being displayed by the same color.

**Comment by davchana** [comment]
WhatsApp app colors each user's name in different colour, maybe first count all users in group, unique them, and assign a random dark hex code colour to each? The background is same for all users.

**Comment by prabhakar267** [comment]
@davchana 
Yes, I think that would be a good solution. Can you raise a PR for same? :smile:

**Comment by davchana** [comment]
@prabhakar267 I would love to, will try, but no commitments :(

Although the snippet I was refering to get random light colours in javascript is:

````javascript
function getRandomColor() {
  var letters = 'BCDEF'.split(''); //out of 123456789ABCDEF Hex Numeral
  var color = '#';
  for (var i = 0; i < 3; i++ ) { //three letter hex colour code
    color += letters[Math.floor(Math.random() * letters.length)];
  }
  return color;
}
````
