### ISSUE TITLE
Add other devices links to FAQ section

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#62]
There is an FAQ **How do I export my chat history from WhatsApp?** in the FAQ section. Currently there is only instructions for Android devices, add the links for iPhone and Windows phone as well.

iPhone: https://faq.whatsapp.com/en/iphone/20888066
Windows: https://faq.whatsapp.com/en/wp/23607796

**Comment by wokrabi** [comment]
I would like to work on it!
