### ISSUE TITLE
 new bug bro : 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by ScopareTutto** [prabhakar267/WA-Reader#73]
It was solved "'ascii' codec can't encode character u'\u200e' in position 0: ordinal not in range(128)" but arose this red sign "  'encoding' is an invalid keyword argument for this function  "

**Comment by prabhakar267** [comment]
I don't think this issue is still persistent. Please verify the same.

**Comment by prabhakar267** [comment]
Closing this since it doesn't seem to persist now. Please feel free to reopen.
