### ISSUE TITLE
WA Reader locally does not work w/o further explanation

### ISSUE THREAD

**Issue by Kassiopeia-2002** [prabhakar267/WA-Reader#75]
Hi, I've downloaded the python 3.9 to run the WA Reader locally, but unfortunately it doesn't work :-(
It's not clear how to make all setups as described - especially the part "source venv/bin/activate". ???
So, I would like to ask you if there is a detailed manual available for this tool so that a beginner is able to use it?
The very short description you have published is not very helpfull, I'm sorry (but as I said: I'm a beginner w/o experiences at all).
Btw: Python seems to work correctly at my Windows 10 computer.
Thank you very much.
Regards,
Kassiopeia-2002

**Comment by prabhakar267** [comment]
@Kassiopeia-2002 If you follow the setup instructions step-by-step, you should be able to run the project locally.
In case you face any specific issue, please feel free to post that.

**Comment by Kassiopeia-2002** [comment]
@prabhakar267 ,  your are right: "...you should be able..." , but I AM NOT.
I followed the setup instructions step-by-step, but w/o results (except the fact that Python 3.9 seems to run correctly).
Why isn't it possible to give me (and others) a clear description? I can't understand it. 

But ok, lets go through your explanations:

“_**Requires Python3 to run locally. See instructions to setup Python3.**_”
  Which instructions? There is none specific (or better: all about Python). I can download Python and install it - ok, and this I’ve done so.

• “_**Clone the project from source**_”
   I’ve downloaded WA-Reader via your link, opened the ZIP-file and stored the content at my D-Drive with the directory “D:\WA-Reader\WA-Reader-master”

“_git clone https://github.com/prabhakar267/WA-Reader && cd WA-Reader_”
  ??? Haven't I already done that with the last step?? OR what is “git clone …” meaning? Causes error messages at my command editor or Python editor !

• “_**Setup virtual environment**_”
  I’ve tried it with your following two lines (the third line failed!):

“_pip install virtualenv_”  => done successfully with a large confirmation text
“_virtualenv venv --python=python3.7_”  => done successfully with a large confirmation text
(but by the way: why “python3.7 as I’ve downloaded the python3.9.2” ?)
“_source venv/bin/activate_”: No idea what to do here: “Source” isn’t a command at the command editor nor in Python ?? !!

• “_**Install all dependencies**_”
“_pip install -r requirements.txt_”  => Done successfully (as far as I know)

• “**_Run server_**”
“_python app.py_“  => Got a long list of error messages – starting with
"C:\Users\MyName\AppData\Local\Programs\Python\Python39>python D:\WA-Reader\WA-Reader-master\app.py
Traceback (most recent call last):
  File "D:\WA-Reader\WA-Reader-master\app.py", line 8, in <module> app = Flask(__name__) (…)" and so one.

So I’m coming back with my question from my first request: How does WA-Reader run and work correctly? It is still absolutely unclear.
Thank you again.
Regards,
Kassiopeia-2002

**Comment by prabhakar267** [comment]
@Kassiopeia-2002 I think there is a issue with your understanding of virtual environments. 
Can you confirm if the virtual env was setup correctly and you have all the dependencies properly installed?

If you are not familar with the concept of virtual envs, please refer to this blog.
https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python

**Comment by Kassiopeia-2002** [comment]
@prabhakar267, please read my comments below…

 

Von: Prabhakar Gupta ***@***.***> 
Gesendet: Montag, 29. März 2021 17:45
An: prabhakar267/WA-Reader ***@***.***>
Cc: Kassiopeia-2002 ***@***.***>; Mention ***@***.***>
Betreff: Re: [prabhakar267/WA-Reader] WA Reader locally does not work w/o further explanation (#75)

 

@Kassiopeia-2002 <https://github.com/Kassiopeia-2002>  I think there is a issue with your understanding of virtual environments.
Can you confirm if the virtual env was setup correctly and you have all the dependencies properly installed?

No, I’m not sure because lots of commands (from your instruction or the instruction mentioned by www.dabapps... ) didn’t work

If you are not familar with the concept of virtual envs, please refer to this blog.
https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python

I’ve tried to understand what they are meaning there, but the instructions you have linked to are NOT comprehensible for beginners and do not work, sorry. 
Now, as you are not able to help me, I have decided to give up. I’ve wasted 2 days for that, 2 days too much.
Your application IS NOT WORKING for someone who is not familiar with Python, it seems to be an application for specialists ONLY, and this is what I regret very much.
I have no idea why you have no intention to make your tool usable for all.
I’m very disappointed from you, sorry.

Regards,
Kassiopeia-2002

**Comment by prabhakar267** [comment]
Closing this issue because of disappointment.
