### ISSUE TITLE
Makes problem with heroku

### ISSUE THREAD

**Issue by SuperSanglap** [prabhakar267/WA-Reader#76]
The code works fine in localhost but throws application error in heroku server with the file app.py

**Comment by prabhakar267** [comment]
@SuperSanglap the app seems to work just fine for me, can you elaborate on the issue?

**Comment by SuperSanglap** [comment]
> @SuperSanglap the app seems to work just fine for me, can you elaborate on the issue?

Actually Sir, I am unable to find out the real issue, Everything works fine on the localhost but don't know what happens with the Heroku Server, can you please check the source code? Thank You! https://github.com/supersanglap/Xport-View
