### ISSUE TITLE
Problem when uploading a valid text file?

### ISSUE THREAD

**Issue by stealther00** [prabhakar267/WA-Reader#9]
I try uploading a valid (quite long) .txt file of a chat I emailed to myself but I get a `It wasn't a valid text file or we were not able to convert it!` error message when I try uploading it? I'm not sure what the problem is- none of the chats I try work, even from 2 different phones. I tried uploading on my localhost and on the website http://prabhakargupta.com/projects/whatsapp-reader/ - Neither of which work.

**Comment by prabhakar267** [comment]
@stealther00 could you share a sample chat file so that i could reproduce the bug

**Comment by n1trux** [comment]
Here's how it looked when I copy&pasted WhatsApp messages from my conversation:

    [00:42, 9.9.2017] Jérôme Boateng: So what's Qt?                        
    [00:47, 9.9.2017] +33 123 45678901: it's a library which you can use to display stuff independent from the display server. Qt is translated platform independently, so it works on Linux, Windows, Mac OS X and possibly others.                        

There's a lot of spaces at the end of each message; my locale is de_DE.

**Comment by prabhakar267** [comment]
@stealther00 I have updated the code and did a lot of refactoring :smile: 
Kindly check the updated link https://whatsapp-reader.herokuapp.com/

Feel free to open the issue again if you face the same problem again
