### ISSUE TITLE
whatsapp-reader.herokuapp.com is not working

### ISSUE THREAD

**Issue by santfirax** [prabhakar267/WA-Reader#90]
Hi, all. When visitting [whatsapp-reader.herokuapp.com](https://whatsapp-reader.herokuapp.com/) it says Application error. I am guessing this is for the new Heroku pricing plan. Is there a steps on how to deploy this to heroku for a private website or any chance to get the project back up ?

**Comment by prabhakar267** [comment]
@santfirax There are no plans to move this to a server as of now. If this changes in future, I will update the repo.
Thanks for your interest. You can continue to use the app locally.
